### ISSUE TITLE
Instance launches as x86 emulated instead of ARM native on Apple Silicon M1

### ISSUE THREAD

**Issue by hakasapl** [ATLauncher/ATLauncher#684]
**Describe the bug**
When ARM support is checked in settings, and I launch a 1.19.2 instance on an M1 Pro Macbook Pro (Apple Silicon ARM), the game still launches in `intel` mode, as indicated by the Mac OS system activity monitor.

**To Reproduce**

1. Verify "ARM Support" is enabled in settings
2. Create a fabric instance and install fabric API only
3. Launch instance
4. Check activity monitor to see if the game is running on `Apple` mode, or `Intel` mode.

**Expected behavior**
While ATLauncher itself can run on intel x86 mode, I would expect the game to launch in native `Apple` ARM mode.

**Logs**
<details>
  <summary>ATLauncher log which includes starting up the instance.</summary>
  
```
[18/12/2022 21:57:34 PM] Organising filesystem
[18/12/2022 21:57:34 PM] ATLauncher Version: 3.4.22.1
[18/12/2022 21:57:34 PM] App Arguments: []
[18/12/2022 21:57:34 PM] JVM Arguments: ["-Duser.dir\u003d**USERSDIR**","-Dapple.laf.useScreenMenuBar\u003dtrue","-Djna.nosys\u003dtrue","-Djava.net.preferIPv4Stack\u003dtrue","-Dawt.useSystemAAFontSettings\u003don","-Dswing.aatext\u003dtrue"]
[18/12/2022 21:57:34 PM] Java Version: Java 8 (1.8.0_351)
[18/12/2022 21:57:34 PM] Java Path: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
[18/12/2022 21:57:34 PM] 64 Bit Java: true
[18/12/2022 21:57:34 PM] RAM Available: 32768MB
[18/12/2022 21:57:34 PM] Launcher Directory: **USERSDIR**
[18/12/2022 21:57:34 PM] Using Mac App? Yes
[18/12/2022 21:57:34 PM] GPU: Apple M1 Pro (Apple (0x106b)) unknown 0MB VRAM
[18/12/2022 21:57:35 PM] CPU: Apple M1 Pro 10 cores/10 threads
[18/12/2022 21:57:35 PM] Operating System: macOS (13.0 build 22A380)
[18/12/2022 21:57:35 PM] Bitness: 64
[18/12/2022 21:57:35 PM] Uptime: 1502680
[18/12/2022 21:57:35 PM] Manufacturer: Apple
[18/12/2022 21:57:35 PM] Showing splash screen and loading everything
[18/12/2022 21:57:35 PM] Checking for updated files!
[18/12/2022 21:57:36 PM] Finished downloading updated files!
[18/12/2022 21:57:36 PM] Launcher finished loading everything
[18/12/2022 21:57:36 PM] Launcher opening
[18/12/2022 21:57:36 PM] Made By Bob*
[18/12/2022 21:57:36 PM] *(Not Actually)
[18/12/2022 21:57:36 PM] Setting up Bottom Bar
[18/12/2022 21:57:36 PM] Finished Setting up Bottom Bar
[18/12/2022 21:57:36 PM] Setting up Tabs
[18/12/2022 21:57:37 PM] Finished Setting up Tabs
[18/12/2022 21:57:37 PM] Showing Launcher
[18/12/2022 21:57:39 PM] java.lang.NoSuchMethodError: accessibilityHitTest
[18/12/2022 21:57:39 PM] Preparing for launch!
[18/12/2022 21:57:41 PM] Launching pack Minecraft 1.19.2 for Minecraft 1.19.2
[18/12/2022 21:57:41 PM] Logging into Minecraft!
[18/12/2022 21:57:41 PM] Loader: Fabric 0.14.11
[18/12/2022 21:57:41 PM] Mods:
[18/12/2022 21:57:41 PM]  - /fabric-api-0.69.0+1.19.2.jar (Added)
[18/12/2022 21:57:41 PM] Launching Minecraft with the following arguments (user related stuff has been removed): [USERSDIR/runtimes/minecraft/java-runtime-gamma/mac-os/java-runtime-gamma/jre.bundle/Contents/Home/bin/java, -XX:-OmitStackTraceInFastThrow, -Xms512M, -Xmx4096M, -XX:MetaspaceSize=256M, -Duser.language=en, -Duser.country=US, -Dfml.log.level=INFO, -Dlog4j.configurationFile=USERSDIR/assets/log_configs/client-1.12.xml, -Dapple.laf.useScreenMenuBar=true, -Xdock:name="Vanilla 1.19.2", -XX:+UnlockExperimentalVMOptions, -XX:+UseG1GC, -XX:G1NewSizePercent=20, -XX:G1ReservePercent=20, -XX:MaxGCPauseMillis=50, -XX:G1HeapRegionSize=32M, -XstartOnFirstThread, -Xss1M, -Djava.library.path=USERSDIR/temp/natives-265abe91696f411d9419fcda266a46d3, -Dminecraft.launcher.brand=ATLauncher, -Dminecraft.launcher.version=3.4.22.1, -cp, USERSDIR/libraries/net/fabricmc/fabric-loader/0.14.11/fabric-loader-0.14.11.jar:USERSDIR/libraries/net/fabricmc/intermediary/1.19.2/intermediary-1.19.2.jar:USERSDIR/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar:USERSDIR/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar:USERSDIR/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar:USERSDIR/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar:USERSDIR/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar:USERSDIR/libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar:USERSDIR/libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar:USERSDIR/libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar:USERSDIR/libraries/org/ow2/asm/asm-util/9.3/asm-util-9.3.jar:USERSDIR/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar:USERSDIR/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar:USERSDIR/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar:USERSDIR/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar:USERSDIR/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar:USERSDIR/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar:USERSDIR/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar:USERSDIR/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.0/log4j-slf4j18-impl-2.17.0.jar:USERSDIR/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar:USERSDIR/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar:USERSDIR/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar:USERSDIR/libraries/io/netty/netty-common/4.1.77.Final/netty-common-4.1.77.Final.jar:USERSDIR/libraries/io/netty/netty-buffer/4.1.77.Final/netty-buffer-4.1.77.Final.jar:USERSDIR/libraries/io/netty/netty-codec/4.1.77.Final/netty-codec-4.1.77.Final.jar:USERSDIR/libraries/io/netty/netty-handler/4.1.77.Final/netty-handler-4.1.77.Final.jar:USERSDIR/libraries/io/netty/netty-resolver/4.1.77.Final/netty-resolver-4.1.77.Final.jar:USERSDIR/libraries/io/netty/netty-transport/4.1.77.Final/netty-transport-4.1.77.Final.jar:USERSDIR/libraries/io/netty/netty-transport-native-unix-common/4.1.77.Final/netty-transport-native-unix-common-4.1.77.Final.jar:USERSDIR/libraries/io/netty/netty-transport-classes-epoll/4.1.77.Final/netty-transport-classes-epoll-4.1.77.Final.jar:USERSDIR/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:USERSDIR/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar:USERSDIR/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar:USERSDIR/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar:USERSDIR/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar:USERSDIR/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar:USERSDIR/libraries/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar:USERSDIR/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar:USERSDIR/libraries/com/mojang/authlib/3.11.49/authlib-3.11.49.jar:USERSDIR/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar:USERSDIR/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar:USERSDIR/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:USERSDIR/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar:USERSDIR/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar:USERSDIR/libraries/org/apache/logging/log4j/log4j-api/2.17.0/log4j-api-2.17.0.jar:USERSDIR/libraries/org/apache/logging/log4j/log4j-core/2.17.0/log4j-core-2.17.0.jar:USERSDIR/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar:USERSDIR/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-macos.jar:USERSDIR/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-macos-arm64.jar:USERSDIR/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar:USERSDIR/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-macos.jar:USERSDIR/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-macos-arm64.jar:USERSDIR/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar:USERSDIR/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-macos.jar:USERSDIR/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-macos-arm64.jar:USERSDIR/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar:USERSDIR/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-macos.jar:USERSDIR/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-macos-arm64.jar:USERSDIR/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar:USERSDIR/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-macos.jar:USERSDIR/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-macos-arm64.jar:USERSDIR/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar:USERSDIR/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-macos.jar:USERSDIR/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-macos-arm64.jar:USERSDIR/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar:USERSDIR/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-macos.jar:USERSDIR/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-macos-arm64.jar:USERSDIR/libraries/com/mojang/text2speech/1.13.9/text2speech-1.13.9.jar:USERSDIR/libraries/ca/weblite/java-objc-bridge/1.1/java-objc-bridge-1.1.jar:USERSDIR/libraries/net/minecraft/client/1.19.2/client-1.19.2.jar, net.fabricmc.loader.impl.launch.knot.KnotClient, --username, REDACTED, --version, 1.19.2, --gameDir, USERSDIR/instances/Vanilla1192, --assetsDir, USERSDIR/assets, --assetIndex, 1.19, --uuid, REDACTED, --accessToken, REDACTED, --userType, msa, --versionType, release, --width=854, --height=480]
[18/12/2022 21:57:43 PM] [main/INFO] Loading Minecraft 1.19.2 with Fabric Loader 0.14.11
[18/12/2022 21:57:43 PM] 	- fabric-api 0.69.0+1.19.2
[18/12/2022 21:57:43 PM] 	- fabric-api-base 0.4.13+0d0f210290 via fabric-api
[18/12/2022 21:57:43 PM] 	- fabric-api-lookup-api-v1 1.6.12+93d8cb8290 via fabric-api
[18/12/2022 21:57:43 PM] 	- fabric-biome-api-v1 9.0.20+0d0f210290 via fabric-api
[18/12/2022 21:57:43 PM] 	- fabric-block-api-v1 1.0.1+12bfe4ea90 via fabric-api
[18/12/2022 21:57:43 PM] 	- fabric-blockrenderlayer-v1 1.1.22+c6af733c90 via fabric-api
[18/12/2022 21:57:43 PM] 	- fabric-client-tags-api-v1 1.0.3+b35fea8390 via fabric-api
[18/12/2022 21:57:43 PM] 	- fabric-command-api-v1 1.2.13+f71b366f90 via fabric-api
[18/12/2022 21:57:43 PM] 	- fabric-command-api-v2 2.1.9+93d8cb8290 via fabric-api
[18/12/2022 21:57:43 PM] 	- fabric-commands-v0 0.2.30+df3654b390 via fabric-api
[18/12/2022 21:57:43 PM] 	- fabric-containers-v0 0.1.38+df3654b390 via fabric-api
[18/12/2022 21:57:43 PM] 	- fabric-content-registries-v0 3.4.4+6064db2a90 via fabric-api
[18/12/2022 21:57:43 PM] 	- fabric-convention-tags-v1 1.2.0+27265b3490 via fabric-api
[18/12/2022 21:57:43 PM] 	- fabric-crash-report-info-v1 0.2.7+aeb40ebe90 via fabric-api
[18/12/2022 21:57:43 PM] 	- fabric-data-generation-api-v1 5.3.3+ad31814d90 via fabric-api
[18/12/2022 21:57:43 PM] 	- fabric-dimensions-v1 2.1.33+0d0f210290 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-entity-events-v1 1.5.2+9244241690 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-events-interaction-v0 0.4.31+6eb9a2a190 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-events-lifecycle-v0 0.2.31+df3654b390 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-game-rule-api-v1 1.0.23+c6af733c90 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-item-api-v1 1.6.1+fa140d5990 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-item-groups-v0 0.3.36+9244241690 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-key-binding-api-v1 1.0.23+aaaf9d3390 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-keybindings-v0 0.2.21+df3654b390 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-lifecycle-events-v1 2.2.2+9244241690 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-loot-api-v2 1.1.10+83a8659290 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-loot-tables-v1 1.1.13+9e7660c690 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-message-api-v1 5.0.5+93d8cb8290 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-mining-level-api-v1 2.1.21+33fbc73890 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-models-v0 0.3.19+c6af733c90 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-networking-api-v1 1.2.8+3b1d070f90 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-networking-v0 0.3.25+df3654b390 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-object-builder-api-v1 4.1.3+06e0e25190 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-particles-v1 1.0.12+79adfe0a90 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-registry-sync-v0 0.9.29+9244241690 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-renderer-api-v1 1.1.0+e7aeff4590 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-renderer-indigo 0.6.17+aeb40ebe90 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-renderer-registries-v1 3.2.22+df3654b390 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-rendering-data-attachment-v1 0.3.17+0d0f210290 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-rendering-fluids-v1 3.0.9+c6af733c90 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-rendering-v0 1.1.25+df3654b390 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-rendering-v1 1.11.1+73145abb90 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-resource-conditions-api-v1 2.1.1+aae9039d90 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-resource-loader-v0 0.8.2+574a764890 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-screen-api-v1 1.0.30+b0bc9a6790 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-screen-handler-api-v1 1.3.4+1cc24b1b90 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-sound-api-v1 1.0.1+c4f28df590 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-textures-v0 1.0.22+aeb40ebe90 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-transfer-api-v1 2.1.3+9d081d6490 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabric-transitive-access-wideners-v1 1.3.2+42d99c3290 via fabric-api
[18/12/2022 21:57:44 PM] 	- fabricloader 0.14.11
[18/12/2022 21:57:44 PM] 	- java 17
[18/12/2022 21:57:44 PM] [main/INFO] Loading 53 mods:	- minecraft 1.19.2
[18/12/2022 21:57:44 PM] [main/INFO] SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:**USERSDIR**/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[18/12/2022 21:57:44 PM] [main/INFO] Compatibility level set to JAVA_16
[18/12/2022 21:57:44 PM] [main/INFO] Compatibility level set to JAVA_17
[18/12/2022 21:57:45 PM] Completely ignored arguments: []
[18/12/2022 21:57:46 PM] [main/WARN] Configuration conflict: there is more than one oshi.properties file on the classpath
[18/12/2022 21:57:46 PM] [main/WARN] Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[18/12/2022 21:57:51 PM] [main/INFO] Building optimized datafixer
[18/12/2022 21:57:58 PM] [Render thread/INFO] Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18/12/2022 21:58:02 PM] [Render thread/INFO] Setting user: **MINECRAFTUSERNAME**
[18/12/2022 21:58:03 PM] [Render thread/INFO] [Indigo] Registering Indigo renderer!
[18/12/2022 21:58:05 PM] [Render thread/INFO] Backend library: LWJGL version 3.3.1 SNAPSHOT
[18/12/2022 21:58:07 PM] [Render thread/INFO] Reloading ResourceManager: Default, Fabric Mods (Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Client Tags, Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Sound API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader)
[18/12/2022 21:58:17 PM] [Worker-Bootstrap-3/INFO] 4283 Datafixer optimizations took 26092 milliseconds
[18/12/2022 21:58:17 PM] [Render thread/WARN] Missing sound for event: minecraft:item.goat_horn.play
[18/12/2022 21:58:17 PM] [Render thread/WARN] Missing sound for event: minecraft:entity.goat.screaming.horn_break
[18/12/2022 21:58:17 PM] [Render thread/INFO] OpenAL initialized on device CoreAudio Default
[18/12/2022 21:58:17 PM] [Render thread/INFO] Sound engine started
[18/12/2022 21:58:17 PM] [Render thread/INFO] Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[18/12/2022 21:58:17 PM] [Render thread/INFO] Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[18/12/2022 21:58:17 PM] [Render thread/INFO] Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[18/12/2022 21:58:17 PM] [Render thread/INFO] Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[18/12/2022 21:58:17 PM] [Render thread/INFO] Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[18/12/2022 21:58:17 PM] [Render thread/INFO] Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[18/12/2022 21:58:17 PM] [Render thread/INFO] Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[18/12/2022 21:58:18 PM] [Render thread/WARN] Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[18/12/2022 21:58:18 PM] [Render thread/INFO] Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[18/12/2022 21:58:18 PM] [Render thread/INFO] Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[18/12/2022 21:58:18 PM] [Render thread/INFO] Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[18/12/2022 21:58:23 PM] 
```
</details>

**System information (please complete the following information, or remove if not applicable):**

- Mac OS Ventura
- Macbook Pro M1 Pro Chip

```
$ java -version
java version "1.8.0_351"
Java(TM) SE Runtime Environment (build 1.8.0_351-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.351-b10, mixed mode)
```

**Additional context**
I understand this feature is still in beta - let me know if there is a better place to report bugs on the ARM feature.

**Comment by RyanTheAllmighty** [comment]
I believe you need to disable the setting to use java provided by Minecraft then make sure you use an appropriate java arm version. Try that

**Comment by hakasapl** [comment]
I have disabled the ARM support and made sure "Use Java Provided by Minecraft" is checked on the Java tab for settings, but still getting instances running in `intel` mode instead of native ARM `apple` mode.

Maybe I'm misunderstanding the ARM support feature. What is that option providing if not native ARM runtime for the instances?

Thanks for your help!

**Comment by RyanTheAllmighty** [comment]
You need to **disable** the "Use Java Provided by Minecraft" option and provide your own path to a ARM install of Java that you've installed on your own system.

We do not provide ARM based Java since we use the system vanilla Minecraft does for runtimes, which doesn't include ARM up until more recent versions of Minecraft, so you need to disable "Use Java Provided by Minecraft" and provide a path to your own ARM based java, otherwise it will launch as intel.

The ARM support feature is there to use correct native libraries, you still need to manage your own Java installations

**Comment by hakasapl** [comment]
Ah - sorry, I misunderstood your first comment. Here's what I did on my macbook:

1. Install openjdk 17 (1.19 is java 17): `brew install openjdk@17` - this by default installs an arm version.
    1. Verify ARM with: `file $(brew --prefix openjdk@17)/bin/java`
1. Uncheck `Use Java Provided by Minecraft` in instance options
1. Check `Enable ARM Support` in the general settings.
1. Specify the java path as `/opt/homebrew/opt/openjdk@17` if you have a default homebrew installation.

The instance now launches as `Apple` instead of `Intel`.

Thanks for your help! I have a quick question just to satisfy my curiosity:

> We do not provide ARM based Java since we use the system vanilla Minecraft does for runtimes, which doesn't include ARM up until more recent versions of Minecraft, so you need to disable "Use Java Provided by Minecraft" and provide a path to your own ARM based java, otherwise it will launch as intel.

Since 1.19 and higher comes with a native ARM java version that the minecraft launcher launches with, what makes atlauncher default to x86 java for 1.19 instances when using Java provided by minecraft? Is this feature that can be implemented - ie. a check that uses the ARM java provided my minecraft instead of x86 if the system is ARM? If so, could you point me to where in the source this happens? I'd love to contribute a PR if I can wrap my head around it.

Thanks again!

**Comment by RyanTheAllmighty** [comment]
Nice. Yeah it should be using the java Mojang provides for those versions, but looks like it actually doesn't due to a bug.

I'll fix it so it should use that runtime for apple silicone. Mac is the most neglected platform unfortunately simply because I don't have access to a mac, renting a cloud based mac is quite expensive and it doesn't emulate well, so unfortunately a lot of things on Mac get left behind.

But it's part of my focus over the holidays to hopefully get Mac compatibility back up there including back porting Mojangs runtimes so it's available for all MC versions, not just 1.19+.

So I'll use this issue to track backporting those runtimes to all MC versions for Mac, so then hopefully you can just turn the setting back on and it should just work without having to worry about it.

**Comment by hakasapl** [comment]
Awesome! I'd be happy to build the master branch on my macbook to test your mac-related changes for this issue, just let me know when your commits are in for that.

**Comment by RyanTheAllmighty** [comment]
Shouldn't need to build it, the latest master builds are always available via https://atl.pw/launcher-nightly which is a zip with each platform (exe for windows, jar for all platforms and zip for the Mac app)

**Comment by RyanTheAllmighty** [comment]
This should be good now. I've released 3.4.23.0 which now uses custom runtimes for most Minecraft versions that didn't before that are ARM native. Completely untested, but should be okay, I hope anyway

**Comment by RyanTheAllmighty** [comment]
Okay so had to disable it for the legacy jre versions, 1.17 and earlier I believe it is, due to there being no ARM lwjgl 2 libraries so it's running ARM java but with x64 lwjgl binaries so it complains. Might be a bit trickier to fix that one

**Comment by hakasapl** [comment]
From my initial testing I'm seeing the same behavior as before, the `1.19.3` instance launches in x86 emulated mode. Here's the log from the instance launch:

https://paste.atlauncher.com/view/85fcd559-9940-492f-aedd-87b7afcae101

From the log it actually looks like it's grabbing the right ARM runtime, but in the event viewer I still see the launched instance as running in "intel" (x86 emulated) mode. I wonder if this is because the launcher itself is initially running in intel mode, so any forked processes cannot go back to native mode? Although my previous workaround still works so that wouldn't explain it.

**Comment by RyanTheAllmighty** [comment]
Is there a `runtimes/minecraft/java-runtime-gamma/mac-os-arm64` folder? It should be downloading that and running that, but doesn't look like it in your case

**Comment by hakasapl** [comment]
I have a `runtimes/minecraft/java-runtime-gamma/mac-os` folder, but not `mac-os-arm64`
